language: ruby
bundler_args: --without development --deployment
cache: bundler
services:
  - mongodb
rvm:
  - 1.9.3-p0
before_script:
  - cp config/mongoid.travis.yml config/mongoid.yml
script:
  - mkdir -p tmp/export
  - RAILS_ENV=test bundle exec rake db:migrate
  - xvfb-run bundle exec rspec
