language: ruby
services:
  - mongodb
rvm:
  - 1.9.3
before_script:
  - cp config/mongoid.travis.yml config/mongoid.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - xvfb-run rspec
