# Html5BoilerplateHelper will first check your ENV and
# then this yml file for these values. If they are both
# empty, the google code block will not be used.
#
# e.g. ENV['GOOGLE_ACCOUNT_ID'] || yml[:google_account_id]
# e.g. ENV['GOOGLE_API_KEY'] || yml[:google_api_key]
#
#
# IDX3.1 exports to: homegate.ch, immoscout24.ch, home.ch, immostreet.ch
# immostreet.ch does not supply a test account, all others do

defaults: &defaults
  google_account_id: ''
  google_api_key: ''
  google_maps_api_key: 'AIzaSyCNWg9D3wR2T69wlEu6ARAtNdPSgAN-N9w'
  idx301:
    # homegate
    homegate:
      agency_id: 'almtest'
      sender_id: 'AlfredMuellerWebsite_HomegateExporter'
      ftp:
        host: '62.65.135.69'
        username: 'almtest'
        password: 'cal31cium'
    # immoscout24
    immoscout24:
      agency_id: '180571_vision'
      sender_id: 'AlfredMuellerWebsite_ImmoscoutExporter'
      ftp:
        host: 'ftp.immoscout24.ch'
        username: '180571_vision'
        password: 'cdzqvxfysy'
    home_ch:
      agency_id: '75680'
      sender_id: 'AlfredMuellerWebsite_HomechExporter'
      ftp:
        host: 'idx.home.ch'
        username: '75680'
        password: 'pwd475680'

development:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults
  idx301:
    my_portal:
      agency_id: 'swag'
      sender_id: 'AlfredMuellerWebsite_SwagExporter'
      ftp:
        host: 'localhost'
        username: 'swagger'
        password: 'swaggerbagmovement'

production:
  google_account_id: ''
  google_api_key: ''
  google_maps_api_key: 'AIzaSyCNWg9D3wR2T69wlEu6ARAtNdPSgAN-N9w'
  idx301:
    # homegate
    homegate:
      agency_id: 'alm'
      sender_id: 'AlfredMuellerWebsite_HomegateExporter'
      ftp:
        host: 'ftp.homegate.ch'
        username: 'alm'
        password: 'neu33hof'
    # add immoscout 24
    # add home.ch
    # add immostreet.ch

