# Html5BoilerplateHelper will first check your ENV and
# then this yml file for these values. If they are both
# empty, the google code block will not be used.
#
# e.g. ENV['GOOGLE_ACCOUNT_ID'] || yml[:google_account_id]
# e.g. ENV['GOOGLE_API_KEY'] || yml[:google_api_key]
#
defaults: &defaults
  google_account_id: ''
  google_api_key: ''
  google_maps_api_key: 'AIzaSyCNWg9D3wR2T69wlEu6ARAtNdPSgAN-N9w'
  homegate:
    agency_id: 'alm'
    ftp:
      host: '62.65.135.69'
      username: 'almtest'
      password: 'cal31cium'

development:
  <<: *defaults
  homegate:
    agency_id: 'almtest'
    ftp:
      host: '62.65.135.69'
      username: 'almtest'
      password: 'cal31cium'

test:
  <<: *defaults

staging:
  <<: *defaults
  homegate:
    agency_id: 'almtest'
    ftp:
      host: '62.65.135.69'
      username: 'almtest'
      password: 'cal31cium'

production:
  <<: *defaults
  homegate:
    agency_id: 'almtest'
    ftp:
      host: '62.65.135.69'
      username: 'almtest'
      password: 'cal31cium'
