# Html5BoilerplateHelper will first check your ENV and
# then this yml file for these values. If they are both
# empty, the google code block will not be used.
#
# e.g. ENV['GOOGLE_ACCOUNT_ID'] || yml[:google_account_id]
# e.g. ENV['GOOGLE_API_KEY'] || yml[:google_api_key]
#
#
# IDX3.1 exports to: homegate.ch, immoscout24.ch, home.ch, immostreet.ch
# immostreet.ch does not supply a test account, all others do

defaults: &defaults
  google_account_id: ''
  google_api_key: ''
  google_maps_api_key: 'AIzaSyCNWg9D3wR2T69wlEu6ARAtNdPSgAN-N9w'
  idx301:
    - provider: 'homegate'
      agency_id: 'almtest'
      sender_id: 'AlfredMuellerWebsite_HomegateExporter'
      video_support: true
      host: '62.65.135.69'
      username: 'almtest'
      password: 'cal31cium'
      offices:
        - camorino
    - provider: 'homegate'
      agency_id: 'almtest'
      sender_id: 'AlfredMuellerWebsite_HomegateExporter'
      video_support: true
      host: '62.65.135.69'
      username: 'almtest'
      password: 'cal31cium'
      offices:
        - baar


development:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults
  idx301:
    - provider: 'my_portal'
      agency_id: 'swag'
      sender_id: 'AlfredMuellerWebsite_SwagExporter'
      video_support: false
      host: 'localhost'
      username: 'swagger'
      password: 'swaggerbagmovement'
      offices:
        - camorino

production:
  google_account_id: ''
  google_api_key: ''
  google_maps_api_key: 'AIzaSyCNWg9D3wR2T69wlEu6ARAtNdPSgAN-N9w'
  idx301:
    - provider: 'homegate'
      agency_id: 'alm'
      sender_id: 'AlfredMuellerWebsite_HomegateExporter'
      video_support: true
      host: 'ftp.homegate.ch'
      username: 'alm'
      password: 'neu33hof'
      offices:
        - baar

    - provider: 'homegate'
      agency_id: 'almcam'
      sender_id: 'AlfredMuellerWebsite_HomegateExporter'
      video_support: true
      host: 'ftp.homegate.ch'
      username: 'almcam'
      password: 'frei77tag'
      offices:
        - camorino

    - provider: 'homegate'
      agency_id: 'almmar'
      sender_id: 'AlfredMuellerWebsite_HomegateExporter'
      video_support: true
      host: 'ftp.homegate.ch'
      username: 'almmar'
      password: 'lon99don'
      offices:
        - marin

    - provider: 'home_ch'
      agency_id: '75680'
      sender_id: 'AlfredMuellerWebsite_HomechExporter'
      video_support: true
      host: 'idx.home.ch'
      username: '75680'
      password: 'pwd475680'
      offices:
        - baar

    - provider: 'home_ch'
      agency_id: '75847'
      sender_id: 'AlfredMuellerWebsite_HomechExporter'
      video_support: true
      host: 'idx.home.ch'
      username: '75847'
      password: 'pwd475847'
      offices:
        - marin

    - provider: 'home_ch'
      agency_id: '75848'
      sender_id: 'AlfredMuellerWebsite_HomechExporter'
      video_support: true
      host: 'idx.home.ch'
      username: '75848'
      password: 'pwd475848'
      offices:
        - camorino

    - provider: 'immoscout24'
      agency_id: '117874_mueller'
      sender_id: 'AlfredMuellerWebsite_ImmoscoutExporter'
      video_support: false
      host: 'ftp.immoscout24.ch'
      username: '117874_mueller'
      password: '6340baar'
      offices:
        - baar

    - provider: 'immoscout24'
      agency_id: '233060'
      sender_id: 'AlfredMuellerWebsite_ImmoscoutExporter'
      video_support: false
      host: 'ftp.immoscout24.ch'
      username: 'kxbdn75f'
      password: 'udo5xucd64'
      offices:
        - marin

    - provider: 'immoscout24'
      agency_id: '340091'
      sender_id: 'AlfredMuellerWebsite_ImmoscoutExporter'
      video_support: false
      host: 'ftp.immoscout24.ch'
      username: 'vr3selg3'
      password: '8y4clo77dh'
      offices:
        - camorino

    - provider: 'immostreet'
      agency_id: '6557'
      sender_id: 'AlfredMuellerWebsite_ImmostreetExporter'
      video_support: false
      host: 'ftp.immostreet.ch'
      username: 'SC6557'
      password: '8C7Pbz'
      offices:
        - baar

    - provider: 'immostreet'
      agency_id: '6609'
      sender_id: 'AlfredMuellerWebsite_ImmostreetExporter'
      video_support: false
      host: 'ftp.immostreet.ch'
      username: 'SC6609'
      password: 'PrFoNX'
      offices:
        - camorino

    - provider: 'immostreet'
      agency_id: '6568'
      sender_id: 'AlfredMuellerWebsite_ImmostreetExporter'
      video_support: false
      host: 'ftp.immostreet.ch'
      username: 'SC6568'
      password: 'vz91LF'
      offices:
        - marin
