defaults: &defaults
  host: localhost
  allow_dynamic_fields: false
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] || "alfred_mueller_#{Rails.env}" %>

development:
  <<: *defaults
  database: alfred_mueller_development

test:
  <<: *defaults
  database: alfred_mueller_test

staging:
  <<: *defaults
  database: alfred_mueller_staging

# set these environment variables on your prod server
production:
  <<: *defaults
